spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pocs
    username: root
    password: rladhkstn02
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
        hbm2ddl:
          auto: create
        default_batch_fetch_size: 1000
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 300MB

springdoc:
  swagger-ui:
    path: /swagger
  cache:
    disabled: true
  use-fqn: true